# Generated by Django 2.0.2 on 2018-02-04 03:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('types_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='types_management.InsuranceType')),
            ],
        ),
    ]
