# Generated by Django 2.0.2 on 2018-02-04 04:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('types_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancetype',
            name='enums',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
